# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: ghlabels

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: desc
  filters:
    exclude:
      - '^Merge'

snapshot:
  name_template: "{{ .Tag }}-next"

dockers:
  - ids:
      - ghlabels
    image_templates:
      - "ghcr.io/clok/ghlabels:{{ .RawVersion }}"
      - "ghcr.io/clok/ghlabels:latest"

brews:
  - tap:
      owner: clok
      name: homebrew-ghlabels
    homepage: "https://clokwork.net/ghlabels/"
    description: "Simple CLI tool to help manage labels across repos"
    license: "MIT"
    test: |
      system "#{bin}/ghlabels --help"
    install: |
      bin.install "ghlabels"